[package]
name = "amosd"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.12.1", default-features = false, features = ["accessibility", "backend-winit", "compat-1-2", "renderer-winit-skia"] }

[build-dependencies]
slint-build = "1.12.1"
