import { OsdGlobal } from "../osd/global.slint";
import { MusicIcon } from "music-icon.slint";
import { UsageIcon } from "usage-icon.slint";

export component CompleteNotch {
  width: 300px;
  height: 100px;

  VerticalLayout {
    x: 7px;
    y: 19px;
    width: root.width - self.x * 2;
    height: root.height * (3 / 4) - 8px;

    spacing: 5px;

    HorizontalLayout {
      alignment: space-around;

      MusicIcon {
        width: self.height;
      }
      UsageIcon {
        width: self.height;
        text: "CPU usage";
        progress: mod(animation-tick() + 250ms, 1s) / 1s;
      }
      UsageIcon {
        width: self.height;
        text: "RAM usage";
        progress: mod(animation-tick() + 500ms, 1s) / 1s;
      }
      UsageIcon {
        width: self.height;
        text: "Disk usage";
        progress: mod(animation-tick() + 750ms, 1s) / 1s;
      }

      Rectangle {background: #F003; width: self.height;}
      Rectangle {background: #F003; width: self.height;}
      Rectangle {background: #F003; width: self.height;}
      Rectangle {background: #F003; width: self.height;}
    }

    HorizontalLayout {
      alignment: space-around;

      Rectangle {background: #0F03; width: self.height;}
      Rectangle {background: #0F03; width: self.height;}
      Rectangle {background: #0F03; width: self.height;}
      Rectangle {background: #0F03; width: self.height;}

      Rectangle {background: #0F03; width: self.height;}
      Rectangle {background: #0F03; width: self.height;}
      Rectangle {background: #0F03; width: self.height;}
      Rectangle {background: #0F03; width: self.height;}
    }
  }
}

