import {IslandWidget} from "base.slint";
import {OsdGlobal} from "../osd/global.slint";
import {OsdConfig, OsdState} from "../osd/state.slint";
import {OsdClockManager} from "../notch/Clock.slint";

export global OsdMediaManager {
  out property <bool> shown: OsdGlobal.widget == config.name;
  out property <OsdConfig> config: {
    name: "media",
    state: OsdState.Island,
    background: #F1F0ECff,
    foreground: #242785ff,
    accent: #80B0F0ff,
  };

  public function show() {
    OsdGlobal.set-widget(config);
  }
}

component MediaBar {   
  in-out property <float> progress: 0.5;

  in property <string> current-time: "";
  in property <string> max-time: "";

  Text {
    text: current-time;
    color: OsdGlobal.foreground;
    font-size: 9px;
    x: 0px;
    y: 5px;
  }

  Text {
    text: max-time;
    color: OsdGlobal.foreground;
    font-size: 9px;
    x: root.width - self.width;
    y: 5px;
  }

  Rectangle {
    x: 0px;
    y: 0px;

    width: root.width;
    height: 2px;
    border-radius: 2px;

    background: OsdGlobal.foreground;
  }

  Rectangle {
    x: 0px;
    y: 0px;

    width: root.width * progress;
    height: 2px;
    border-radius: 2px;

    background: @linear-gradient(45deg, OsdGlobal.foreground 0%, OsdGlobal.accent 50%, OsdGlobal.accent 100%);
  }

  Rectangle {
    property <length> size: ta.has-hover ? 9px : 0px;

    x: root.width * progress - self.width / 2;
    y: -self.width / 3;

    width: size;
    height: size;
    border-radius: 5px;

    animate width, height {
      duration: 50ms;
    }

    background: OsdGlobal.accent;
    border-color: #FFF;
    border-width: 1px;
  }

  Rectangle {
    x: 0px;
    y: 0px - self.height / 3;
    width: root.width;
    height: 7px;

    ta := TouchArea {
      clicked => {
        root.progress = max(0, min(parent.width, self.mouse-x)) / parent.width;
      }

      moved => {
        if (self.pressed) {
          root.progress = max(0, min(parent.width, self.mouse-x)) / parent.width;
        }
      }
    }
  }
}

component OsdMediaInner inherits IslandWidget {
  Rectangle {
    x: max(0, root.width / root.min-width) * 100px - 85px;
    y: root.height / 2 - self.height / 2;

    width: 90px;
    height: 90px;
    border-radius: 70px;
    border-color: OsdGlobal.foreground;
    border-width: 2px;

    clip: true;

    Image {
      source: @image-url("../assets/SongAlbum.jpg");
      width: parent.width;
      height: parent.height;
      image-fit: ImageFit.cover;
    }
  }

  Rectangle {
    x: ((root.width - self.width - 70px) + (120px)) / 2;
    y: root.height - self.height - 70px;
    width: 250px;
    height: 35px;

    Text {
      x: 0px;
      y: 0px;
      text: "Song name";
      font-size: 16px;
      font-weight: 600;
      color: OsdGlobal.foreground;
    }

    Text {
      x: 0px;
      y: 19px;
      text: "Artist";
      font-size: 12px;
      font-weight: 600;
      color: OsdGlobal.accent;
    }
  }

  MediaBar {
    x: ((root.width - self.width - 70px) + (120px)) / 2;
    y: max(0, root.height / root.target-height) * 50px + 40px;

    width: 250px;

    current-time: "00:30";
    max-time: "01:00";
  }

  HorizontalLayout {
    x: ((root.width - self.width - 70px) + (120px)) / 2;
    y: root.height - self.height + 10px;

    width: 200px;

    alignment: space-between;

    Image {
      source: @image-url("../assets/play-back.svg");
      width: 24px;
      colorize: OsdGlobal.foreground;
    }

    Image {
      source: @image-url("../assets/play.svg");
      width: 24px;
      colorize: OsdGlobal.foreground;
    }

    Image {
      source: @image-url("../assets/play-forward.svg");
      width: 24px;
      colorize: OsdGlobal.foreground;
    }
  }
}

export component OsdMedia inherits IslandWidget {
  if OsdMediaManager.shown: OsdMediaInner { }
}

