export component NotchWidget {
  in property <bool> shown: false;

  min-width: 103px;
  min-height: 20px;
  preferred-width: 100%;
  preferred-height: 100%;

  states [
      hidden when !root.shown: {
        y: -self.height;
        opacity: 0;

        in {
          animate y {
            duration: 100ms;
          }
          animate opacity {
            duration: 300ms;
          }
        }

        out {
          animate y {
            duration: 200ms;
          }

          animate opacity {
            duration: 300ms;
          }
        }
      }
  ]

  @children
}

