import { OsdState, OsdConfig } from "./state.slint";

export global OsdGlobal {
  in-out property <OsdConfig> config: {
    name: "clock",
    background: #000,
    foreground: #FFF,
    accent: #888,
    state: OsdState.Notch,
  };

  out property <brush> background: config.background;
  out property <brush> foreground: config.foreground;
  out property <brush> accent: config.accent;
  out property <OsdState> state: config.state;

  out property <bool> is-notch: state == OsdState.Notch;
  out property <bool> is-notch-open: state == OsdState.NotchOpen;
  out property <bool> is-island: state == OsdState.Island;

  out property <duration> animation-start: animation-tick();
  out property <bool> old-island: is-island;

  out property <string> widget: config.name;

  public function set-widget(new-config: OsdConfig) {
    animation-start = animation-tick();
    old-island = is-island;

    config = new-config;
  }

  public function set-state(new-state: OsdState) {
    animation-start = animation-tick();
    old-island = is-island;
    config.state = new-state;
  }
}
